Issue #2026 Retry Subworkflow Mechanism
Netflix/conductor pull request #2038
Opened 2021-01-06 11:55 UTC by mehmet-islamoglu

Issue #2026: 

The requested changes from the previous Pull Request are made: 

Pull Request #2025 Fixed the retry mechanism for subworkflows so that retry starts from the last failed task. 

co-authors: @grkn @azb96

Please guide through the contribution process @kishorebanala @apanicker-nflx @aravindanr @jfernandez

2021-01-06 12:20 UTC, mehmet-islamoglu commented
Our build is failing with this error. Can you help us please? 

@kishorebanala @apanicker-nflx @aravindanr @jfernandez

```
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
No stopped containers
> Task :conductor-mysql-persistence:integrationTestDockerComposeUp FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':conductor-mysql-persistence:integrationTestDockerComposeUp'.
> Exit-code 1 when calling docker-compose, stdout: N/A
```

2021-01-08 11:54 UTC, mehmet-islamoglu commented
@kishorebanala could you please review our PR?

2021-01-13 01:29 UTC, kishorebanala requested changes

2021-01-13 01:29 UTC, kishorebanala commented on jersey/src/main/java/com/netflix/conductor/server/resources/WorkflowResource.java
> +    public void retry(@PathParam("workflowId") String workflowId,@QueryParam("retryFromLastFailedTask") boolean retryFromLastFailedTask) {
Naming the parameter as `retryFromLastFailedTask` doesn't seem intuitive. For example, if the workflow doesn't have any subworkflow(s), the default behavior is to retry from last failed task. Setting this parameter `retryFromLastFailedTask` to `false` on retry request would then have no impact.

Instead, how about calling this `resumeSubworkflowTasks` or something similar?

Also, please add `@DefaultValue("false")` to QueryParam (See `restart` definition above for reference).

2021-01-13 01:29 UTC, kishorebanala commented on ui/src/components/workflow/executions/WorkflowAction.js
> +        <Popover id="popover-trigger-hover-focus" title="Retry Last Failed Task from Subworkflow">
+1

2021-01-13 01:29 UTC, kishorebanala commented on test-harness/src/test/java/com/netflix/conductor/tests/integration/AbstractWorkflowServiceTest.java
> +        // poll and fail the first task in sub-workflow
Comment doesn't match with the action.

2021-01-13 01:32 UTC, kishorebanala commented
@mehmet-islamoglu @grkn @azb96 Great work so far, thanks for the contribution.

Regarding your question about progressing the PR, let's finalize the review and we'll take it from there to merge it. In general, after merging to dev, we batch merge dev to master and cut out a new release tag.

2021-01-14 16:38 UTC, mehmet-islamoglu commented
Hello @kishorebanala,

We have completed all of your requested changes. Could you please review our PR again?

2021-01-26 00:17 UTC, kishorebanala approved these changes

2021-01-26 00:17 UTC, merged