update python client with structuring task result
Netflix/conductor pull request #2138
Opened 2021-03-22 14:22 UTC by khang21081995

hi,
i'm adding new way to create task result with clearly structure and adding enumerate task status on python client for newbie choose the correct status of task after processed

2021-03-29 23:32 UTC, kishorebanala requested changes

2021-03-29 23:32 UTC, kishorebanala commented on client/python/kitchensink_workers.py
> +    # return {'status': 'COMPLETED', 'output': {'mod': 5, 'taskToExecute': 'task_1', 'oddEven': 0}, 'logs': ['one','two']}
Please remove this commented out line.

2021-04-11 17:16 UTC, khang21081995 reviewed
remove comment of the old way to return task result

2021-04-12 23:43 UTC, kishorebanala approved these changes

2021-04-12 23:43 UTC, merged