support bulk termination of workflows
Netflix/conductor pull request #2176
Opened 2021-04-14 07:28 UTC by noamlevy81

Pull Request type
----

- [ ] Feature

Changes in this PR
----
added functionality supported by the API to the workflow client.

2021-04-19 23:39 UTC, apanicker-nflx requested changes

2021-04-19 23:39 UTC, apanicker-nflx commented on client/build.gradle
> +    implementation project(':conductor-core')
This dependency seems unnecessary and would bring in a large number of libraries into any application that would use the conductor client.

2021-04-19 23:39 UTC, apanicker-nflx commented on client/src/main/java/com/netflix/conductor/client/http/ClientBase.java
> +import com.netflix.conductor.core.utils.BulkResponse;
A better approach here would be to move the `BulkResponse` object to the `common` module.

2021-04-26 23:29 UTC, apanicker-nflx approved these changes

2021-04-26 23:31 UTC, aravindanr approved these changes

2021-04-26 23:33 UTC, merged