Fix amqp channel and connection creation in order to prevent "unknown delivery tag"
Netflix/conductor pull request #2383
Opened 2021-08-01 08:37 UTC by heinrichcohn

Pull Request type
----

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe):

Changes in this PR
After this PR amqp connection and channel will be created once instead of closing and opening channels each time there is a failure.
Upgrade amqp-client version to 5.13.0

_Describe the new behavior from this PR, and why it's needed_
Amqp connection/channel objects will be created once and amqp client will be responsible of restoring channels in case of a failure. 
After this PR Conductor will be able to acknowledge messages with delivery tags from previous channels and process those messages successfully

_Issue_ 
https://github.com/Netflix/conductor/issues/2382

Alternatives considered
----

No

2021-08-02 17:50 UTC, aravindanr commented
@ritu-p , can you please review this PR?

2021-08-03 21:56 UTC, heinrichcohn commented
@aravindanr  @apanicker-nflx 

As part of this PR i'm upgrading the version of the amqp-client since the current version (5.9.0) contains an issue related to consumer recovery and consumer tags.
Since I updated the relevant dependencies.lock files, the compilation creates the final jar with the right amqp-client version, but if i delete the dependencies.lock files and run "_./gradlew generateLock updateLock saveLock_" to recreate them, the lock files of the **server** and **test-harness** will have the older version 5.9.0 and not 5.13.0. This situation will cause that the final boot jar will have the amp-client:5.9.0 and not 5.13.0.

Updating the following files fix the problem:
**./server/build.gradle**
_implementation( group: 'com.rabbitmq', name: 'amqp-client'){ version{require "${revAmqpClient}"}}_
**and adding to ./server/build.gradle**
_testImplementation( group: 'com.rabbitmq', name: 'amqp-client'){ version{require "${revAmqpClient}"}}_

Are you ok with this approach or you have a better idea?

Thanks

2021-08-04 16:53 UTC, ritu-p requested changes

2021-08-04 16:53 UTC, ritu-p commented on contribs/src/main/java/com/netflix/conductor/contribs/queue/amqp/AMQPObservableQueue.java
> +        if (channel != null) {
Can we also check it the channel is not closed? An existing channel which is already closed will also cause issues

2021-08-04 16:53 UTC, ritu-p commented on contribs/src/main/java/com/netflix/conductor/contribs/queue/amqp/AMQPObservableQueue.java
> -                isChanOpened = false;
Would it make sense to retry channel creation in shutdown listener after a configurable time interval?

2021-08-09 06:21 UTC, heinrichcohn commented
@ritu-p @aravindanr 
I made the requested changes and update the unit-test.
Can you please review and merge if everything is ok?
Thanks

2021-08-09 10:17 UTC, ritu-p approved these changes

2021-08-09 10:18 UTC, ritu-p commented
@heinrichcohn I have approved the changes

2021-08-09 21:14 UTC, merged