[Feature] Support to specify shutdown grace period time for worker
Netflix/conductor pull request #2631
Opened 2021-12-08 15:10 UTC by howaric

Pull Request type
----

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe):

Changes in this PR
----
Add a new parameter 'shutdownGracePeriodSeconds' to TaskRunnerConfigurer which is the timeout of terminating worker thread pool. Default value is 10 seconds, and can't be changed.
A task may cost longer, so it is better to make users can specify the timeout.
Default value is still 10 seconds with this new feature.

Concern: 
I have removed shutdown() method from TaskPollExecutor, it is a default method, and not used by anywhere in this project, I can't see any reason to keep it, please correct me if there is potential problems, thanks.

Alternatives considered
----

2021-12-15 22:39 UTC, aravindanr commented
@howaric Thanks for the pull request. Could you also update the documentation in the `docs` folder? https://netflix.github.io/conductor/gettingstarted/client/#taskrunnerconfigurer

2021-12-15 22:40 UTC, aravindanr requested changes
@howaric Thanks for the pull request. Could you also update the documentation in the docs folder? https://netflix.github.io/conductor/gettingstarted/client/#taskrunnerconfigurer

2021-12-20 23:09 UTC, apanicker-nflx approved these changes

2021-12-20 23:11 UTC, aravindanr approved these changes

2021-12-20 23:11 UTC, merged